# Change these first
owner: rcharlin # Your GitHub organization or username, where this repository lives
repo: webuptime # The name of this repository

sites:
  - name: IMVI
    url: https://imvi.com.ar/
  - name: ATOMO
    url: https://atomodesinflamante.com.ar/
  - name: Gynoderm
    url: https://gynoderm.com.ar/
  - name: Varisedan
    url: https://varisedan.com.ar/
  - name: Bernardo de Irigoyen
    url: http://vpn.imvi.com.ar/
    
    asigneers:
    - rcharlin 

status-website:
 
  baseUrl : /webuptime 
  nombre : Paginas IMVI
 
  
  logoUrl: https://imvi.com.ar/img/logo-imvi.png
  name: Estado de las Web
  introTitle: "Sistema de monitoreo Web para Laboratorios IMVI S.A.."
  introMessage: Gracias por visitarnos
  navbar:
    - title: Status web
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
